stages:
  - build
  - upload
  - release
variables:
  DEBIAN_FRONTEND: noninteractive
  PACKAGE_NAME: yttv
  PACKAGE_REGISTRY_URL: >-
    ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${PACKAGE_NAME}/${CI_COMMIT_TAG}
build_job:
  stage: build
  image: ubuntu:20.04
  script:
    - apt update
    - apt upgrade -y
    - apt install -y python3-pyside2.qtwebenginewidgets git make binutils wget
    - apt install -y --no-install-recommends python3-pip
    - pip3 install -U pyinstaller
    - git submodule update --init --recursive
    - make appimage
    - APP_VERSION=$(cat yttv/__init__.py | grep YTTV_VERSION | cut -d'=' -f 2 | cut -d'"' -f 2)
    - APPIMAGE_FILE=$(basename dist/*.AppImage | sed "s/-x86_64.AppImage/-${APP_VERSION}-x86_64.AppImage/")
    - mv dist/*.AppImage ${APPIMAGE_FILE}
    - echo "APPIMAGE_FILE=${APPIMAGE_FILE}" >> build.env
  artifacts:
    paths:
      - ./*.AppImage
    reports:
      dotenv: build.env
  only:
    - tags
  except:
    - branches
upload_job:
  stage: upload
  image: 'curlimages/curl:latest'
  script:
    - >-
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file ${APPIMAGE_FILE} ${PACKAGE_REGISTRY_URL}/
  only:
    - tags
  except:
    - branches
release_job:
  stage: release
  image: 'registry.gitlab.com/gitlab-org/release-cli:latest'
  script:
    - >-
      release-cli create --name "Release $CI_COMMIT_TAG" --tag-name $CI_COMMIT_TAG
      --assets-link
      "{\"name\":\"${APPIMAGE_FILE}\",\"url\":\"${PACKAGE_REGISTRY_URL}/${APPIMAGE_FILE}\"}"
  only:
    - tags
  except:
    - branches
