version: '3.8'
services:
    yttv_appimage:
        build: .
        container_name: yttv_appimage_c
        command: make appimage
        volumes:
            - .:/app
        working_dir: /app 

    yttv_deb:
        build: .
        container_name: yttv_deb_c
        command: make deb
        volumes:
            - .:/app
        working_dir: /app 